// <auto-generated />
using Luftfartshinder.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luftfartshinder.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Luftfartshinder.Models.ObstacleData", b =>
                {
                    b.Property<int>("ObstacleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ObstacleID"));

                    b.Property<string>("ObstacleCoords")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObstacleDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObstacleHeight")
                        .HasColumnType("int");

                    b.Property<string>("ObstacleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ObstacleID");

                    b.ToTable("Obstacles");
                });
#pragma warning restore 612, 618
        }
    }
}
