// <auto-generated />
using System;
using Luftfartshinder.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luftfartshinder.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20251205093944_SeedSecondPilot")]
    partial class SeedSecondPilot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Luftfartshinder.Models.Domain.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c68c0d2b-a9ed-445b-97c9-d0e9117f7769",
                            Email = "superadmin@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Super",
                            IsApproved = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@KARTVERKET.NO",
                            NormalizedUserName = "SUPERADMIN@KARTVERKET.NO",
                            OrganizationId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEH47+CKFibjiheWX+ESu0lWsKk2kMdbDeq0/1uuZRKqLw+a8CzqP/mDnVKJl7/Kq8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "11756974-ef37-4616-8d32-aa8876ba3607",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kartverket.no"
                        },
                        new
                        {
                            Id = "322acd53-a201-47c6-a7e0-6695690ce677",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1f02907-5bc1-4ded-8baa-8fa8dc5e18c4",
                            Email = "registrar@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Regi",
                            IsApproved = true,
                            LastName = "Strar",
                            LockoutEnabled = false,
                            NormalizedEmail = "REGISTRAR@KARTVERKET.NO",
                            NormalizedUserName = "REGISTRAR",
                            OrganizationId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEKK/tjn9DmfSvd9EhZ1uGpB4grNXZ3L4D07PdU+vRm2QBPdbMk5G1OiekqX1C4B2PA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "21ab13f7-38c5-4a5b-9638-9edff2bf2131",
                            TwoFactorEnabled = false,
                            UserName = "registrar"
                        },
                        new
                        {
                            Id = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "37072807-23f8-4d68-be3e-d8286673dee0",
                            Email = "pilot@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Kaptein",
                            IsApproved = true,
                            LastName = "Pilot",
                            LockoutEnabled = false,
                            NormalizedEmail = "PILOT@KARTVERKET.NO",
                            NormalizedUserName = "PILOT",
                            OrganizationId = 4,
                            PasswordHash = "AQAAAAIAAYagAAAAEKK/tjn9DmfSvd9EhZ1uGpB4grNXZ3L4D07PdU+vRm2QBPdbMk5G1OiekqX1C4B2PA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15a96e31-e9ca-4f24-b6df-eef103708890",
                            TwoFactorEnabled = false,
                            UserName = "pilot"
                        },
                        new
                        {
                            Id = "2e4c55df-6618-5550-c95d-953640f24e13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51b83108-10ea-4ff1-be6b-efb4f27828a4",
                            Email = "pilot2@airambulance.no",
                            EmailConfirmed = false,
                            FirstName = "Anna",
                            IsApproved = true,
                            LastName = "Hansen",
                            LockoutEnabled = false,
                            NormalizedEmail = "PILOT2@AIRAMBULANCE.NO",
                            NormalizedUserName = "PILOT2",
                            OrganizationId = 4,
                            PasswordHash = "AQAAAAIAAYagAAAAEKK/tjn9DmfSvd9EhZ1uGpB4grNXZ3L4D07PdU+vRm2QBPdbMk5G1OiekqX1C4B2PA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e000dfd-3608-4daf-893e-039b9865bd78",
                            TwoFactorEnabled = false,
                            UserName = "pilot2"
                        });
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kartverket"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Norwegian Air Force"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Police"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Norwegian Air Ambulance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Avinor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            ConcurrencyStamp = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            Name = "FlightCrew",
                            NormalizedName = "FLIGHTCREW"
                        },
                        new
                        {
                            Id = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            ConcurrencyStamp = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            Name = "Registrar",
                            NormalizedName = "REGISTRAR"
                        },
                        new
                        {
                            Id = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            ConcurrencyStamp = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "89b2d41d-faa8-45fe-8601-1925778c4c30"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417"
                        },
                        new
                        {
                            UserId = "322acd53-a201-47c6-a7e0-6695690ce677",
                            RoleId = "89b2d41d-faa8-45fe-8601-1925778c4c30"
                        },
                        new
                        {
                            UserId = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
                        },
                        new
                        {
                            UserId = "2e4c55df-6618-5550-c95d-953640f24e13",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.ApplicationUser", b =>
                {
                    b.HasOne("Luftfartshinder.Models.Domain.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luftfartshinder.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Organization", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
