<<<<<<< HEAD
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
<<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119092435_authdbmigration.Designer.cs
=======
>>>>>>> 9be7fd2 (La til flere toasts og modals):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
=======
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
﻿// <auto-generated />
using System;
using Luftfartshinder.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luftfartshinder.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
<<<<<<< HEAD
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119092435_authdbmigration.Designer.cs
    [Migration("20251119092435_authdbmigration")]
    partial class authdbmigration
=======
    [Migration("20251119101206_authmig")]
    partial class authmig
>>>>>>> 985ea00 (Delete, Approve, Reject, Save Note):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
=======
    [Migration("20251120152955_authdbmigration")]
    partial class authdbmigration
>>>>>>> 9be7fd2 (La til flere toasts og modals):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
=======
<<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120154634_authdbmigration2.Designer.cs
    [Migration("20251120154634_authdbmigration2")]
    partial class authdbmigration2
========
    [Migration("20251120152955_authdbmigration")]
    partial class authdbmigration
>>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Luftfartshinder.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            AccessFailedCount = 0,
<<<<<<< HEAD
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119092435_authdbmigration.Designer.cs
                            ConcurrencyStamp = "a95ce37b-4ab4-4b0c-8f09-dcc6d21dea1f",
=======
                            ConcurrencyStamp = "dc6a9db0-e9e4-45ce-b55a-dec9fa9f5073",
>>>>>>> 985ea00 (Delete, Approve, Reject, Save Note):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
=======
                            ConcurrencyStamp = "ade99e60-ec20-4977-b153-f87f84791676",
>>>>>>> 9be7fd2 (La til flere toasts og modals):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
=======
<<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120154634_authdbmigration2.Designer.cs
                            ConcurrencyStamp = "bf060dbb-f309-4295-afea-ad694a945fa0",
========
                            ConcurrencyStamp = "ade99e60-ec20-4977-b153-f87f84791676",
>>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
                            Email = "superadmin@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Super",
                            IsApproved = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@KARTVERKET.NO",
                            NormalizedUserName = "SUPERADMIN@KARTVERKET.NO",
                            PasswordHash = "AQAAAAIAAYagAAAAEH47+CKFibjiheWX+ESu0lWsKk2kMdbDeq0/1uuZRKqLw+a8CzqP/mDnVKJl7/Kq8A==",
                            PhoneNumberConfirmed = false,
<<<<<<< HEAD
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119092435_authdbmigration.Designer.cs
                            SecurityStamp = "d007283e-d252-4447-8610-43c161dce390",
=======
                            SecurityStamp = "04831698-e60f-43af-a6e2-d84b20d53fca",
>>>>>>> 985ea00 (Delete, Approve, Reject, Save Note):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
=======
                            SecurityStamp = "63f4c9f8-aa59-4467-8da6-c2bb9b57f6c3",
>>>>>>> 9be7fd2 (La til flere toasts og modals):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kartverket.no"
=======
<<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120154634_authdbmigration2.Designer.cs
                            SecurityStamp = "d35b80e2-0eab-44f7-b5c7-3e1b6d25688f",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kartverket.no"
                        },
                        new
                        {
                            Id = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0cb27bac-8f93-40b8-8835-a1e4d95a1a13",
                            Email = "pilot@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Kaptein",
                            IsApproved = true,
                            LastName = "Pilot",
                            LockoutEnabled = false,
                            NormalizedEmail = "PILOT@KARTVERKET.NO",
                            NormalizedUserName = "PILOT",
                            PasswordHash = "AQAAAAIAAYagAAAAEKK/tjn9DmfSvd9EhZ1uGpB4grNXZ3L4D07PdU+vRm2QBPdbMk5G1OiekqX1C4B2PA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "59a10fb2-ae05-434f-89de-3d9767f37fb2",
                            TwoFactorEnabled = false,
                            UserName = "pilot"
========
                            SecurityStamp = "63f4c9f8-aa59-4467-8da6-c2bb9b57f6c3",
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kartverket.no"
>>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            ConcurrencyStamp = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            Name = "FlightCrew",
                            NormalizedName = "FLIGHTCREW"
                        },
                        new
                        {
                            Id = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            ConcurrencyStamp = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            Name = "Registrar",
                            NormalizedName = "REGISTRAR"
                        },
                        new
                        {
                            Id = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            ConcurrencyStamp = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "89b2d41d-faa8-45fe-8601-1925778c4c30"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417"
<<<<<<< HEAD
=======
<<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120154634_authdbmigration2.Designer.cs
                        },
                        new
                        {
                            UserId = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
========
>>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
<<<<<<< HEAD
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
========
=======
>>>>>>> 1c7ee01 (La til success message (toast) på index, markers blir på kartet til draft er submitted. Litt registrar refaktorisering):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
﻿// <auto-generated />
using System;
using Luftfartshinder.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luftfartshinder.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
    [Migration("20251117183933_AuthDbMig")]
    partial class AuthDbMig
=======
    [Migration("20251120091742_authmigration")]
    partial class authmigration
>>>>>>> 1c7ee01 (La til success message (toast) på index, markers blir på kartet til draft er submitted. Litt registrar refaktorisering):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Luftfartshinder.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            AccessFailedCount = 0,
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
                            ConcurrencyStamp = "401bfa3c-e784-48d5-abf2-44184f4155f4",
=======
                            ConcurrencyStamp = "009f29c6-becd-435a-bea1-737aba28dad5",
>>>>>>> 1c7ee01 (La til success message (toast) på index, markers blir på kartet til draft er submitted. Litt registrar refaktorisering):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
                            Email = "superadmin@kartverket.no",
                            EmailConfirmed = false,
                            FirstName = "Super",
                            IsApproved = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERADMIN@KARTVERKET.NO",
                            NormalizedUserName = "SUPERADMIN@KARTVERKET.NO",
                            PasswordHash = "AQAAAAIAAYagAAAAEH47+CKFibjiheWX+ESu0lWsKk2kMdbDeq0/1uuZRKqLw+a8CzqP/mDnVKJl7/Kq8A==",
                            PhoneNumberConfirmed = false,
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
                            SecurityStamp = "49b3d5ca-5838-4870-a6cb-eee0a4d98f2c",
=======
                            SecurityStamp = "5d87a9be-dd39-4f67-853f-dcc0fdf41f57",
>>>>>>> 1c7ee01 (La til success message (toast) på index, markers blir på kartet til draft er submitted. Litt registrar refaktorisering):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
                            TwoFactorEnabled = false,
                            UserName = "superadmin@kartverket.no"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            ConcurrencyStamp = "d0fe1bc1-1838-48db-b483-a31510e5a2f6",
                            Name = "FlightCrew",
                            NormalizedName = "FLIGHTCREW"
                        },
                        new
                        {
                            Id = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            ConcurrencyStamp = "89b2d41d-faa8-45fe-8601-1925778c4c30",
                            Name = "Registrar",
                            NormalizedName = "REGISTRAR"
                        },
                        new
                        {
                            Id = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            ConcurrencyStamp = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "d0fe1bc1-1838-48db-b483-a31510e5a2f6"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "89b2d41d-faa8-45fe-8601-1925778c4c30"
                        },
                        new
                        {
                            UserId = "3c1b1dcf-6345-42b9-90fe-45227eb5be5b",
                            RoleId = "66eeb3d3-c3a2-4c2a-8e47-d6513739f417"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Luftfartshinder.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
<<<<<<< HEAD:Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251119101206_authmig.Designer.cs
>>>>>>>> 1f64686 (La til kart preview på registrar details side):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251117183933_AuthDbMig.Designer.cs
=======
>>>>>>> 1c7ee01 (La til success message (toast) på index, markers blir på kartet til draft er submitted. Litt registrar refaktorisering):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120091742_authmigration.Designer.cs
=======
>>>>>>> 9be7fd2 (La til flere toasts og modals):Luftfartshinder/Luftfartshinder/Migrations/AuthDb/20251120152955_authdbmigration.Designer.cs
=======
>>>>>>> 9be7fd20e1fcd6731d8c1ae1553aba716be92fb2
