// <auto-generated />
using System;
using Luftfartshinder.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luftfartshinder.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251205092714_SeedObstaclesAndReports")]
    partial class SeedObstaclesAndReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Obstacle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<double?>("Height")
                        .HasColumnType("double");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("RegistrarNote")
                        .HasColumnType("longtext");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Obstacles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High voltage powerline crossing flight path near Oslo",
                            Height = 45.5,
                            Latitude = 59.913899999999998,
                            Longitude = 10.7522,
                            Name = "High Voltage Powerline",
                            OrganizationId = 4,
                            ReportId = 1,
                            Status = 0,
                            Type = "powerline"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Distribution powerline near residential area in Oslo",
                            Height = 25.0,
                            Latitude = 59.920000000000002,
                            Longitude = 10.76,
                            Name = "Distribution Line",
                            OrganizationId = 4,
                            ReportId = 1,
                            Status = 0,
                            Type = "powerline"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Overhead cable line in Oslo region",
                            Height = 30.0,
                            Latitude = 59.914999999999999,
                            Longitude = 10.755000000000001,
                            Name = "Cable Line",
                            OrganizationId = 4,
                            ReportId = 1,
                            Status = 1,
                            Type = "line"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tall communication mast in Bergen area",
                            Height = 120.0,
                            Latitude = 60.391300000000001,
                            Longitude = 5.3220999999999998,
                            Name = "Communication Mast",
                            OrganizationId = 4,
                            ReportId = 2,
                            Status = 0,
                            Type = "mast"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Radio transmission tower near Bergen",
                            Height = 95.5,
                            Latitude = 60.399999999999999,
                            Longitude = 5.3300000000000001,
                            Name = "Radio Tower",
                            OrganizationId = 4,
                            ReportId = 2,
                            Status = 0,
                            Type = "mast"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Weather monitoring station in Bergen region",
                            Height = 15.0,
                            Latitude = 60.390000000000001,
                            Longitude = 5.3200000000000003,
                            Name = "Weather Station Mast",
                            OrganizationId = 4,
                            ReportId = 2,
                            Status = 2,
                            Type = "point"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Antenna on top of building in Trondheim",
                            Height = 12.5,
                            Latitude = 63.430500000000002,
                            Longitude = 10.395099999999999,
                            Name = "Building Antenna",
                            OrganizationId = 1,
                            ReportId = 3,
                            Status = 0,
                            Type = "point"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Large industrial building complex in Trondheim",
                            Height = 35.0,
                            Latitude = 63.435000000000002,
                            Longitude = 10.4,
                            Name = "Industrial Complex",
                            OrganizationId = 1,
                            ReportId = 3,
                            Status = 0,
                            Type = "area"
                        });
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "pilot",
                            AuthorId = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            OrganizationId = 4,
                            ReportDate = new DateTime(2025, 11, 30, 9, 27, 14, 420, DateTimeKind.Utc).AddTicks(9261),
                            Summary = "Multiple powerline obstacles detected during flight survey",
                            Title = "Powerline Obstacle Report - Oslo Area"
                        },
                        new
                        {
                            Id = 2,
                            Author = "pilot",
                            AuthorId = "1d3b44cf-5507-444f-b84c-842539f13e02",
                            OrganizationId = 4,
                            ReportDate = new DateTime(2025, 12, 2, 9, 27, 14, 420, DateTimeKind.Utc).AddTicks(9538),
                            Summary = "Communication masts and towers identified in flight path",
                            Title = "Mast and Tower Report - Bergen Region"
                        },
                        new
                        {
                            Id = 3,
                            Author = "registrar",
                            AuthorId = "322acd53-a201-47c6-a7e0-6695690ce677",
                            OrganizationId = 1,
                            ReportDate = new DateTime(2025, 12, 4, 9, 27, 14, 420, DateTimeKind.Utc).AddTicks(9543),
                            Summary = "Various urban obstacles including buildings and structures",
                            Title = "Urban Obstacle Survey - Trondheim"
                        });
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Obstacle", b =>
                {
                    b.HasOne("Luftfartshinder.Models.Domain.Report", "Report")
                        .WithMany("Obstacles")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Luftfartshinder.Models.Domain.Report", b =>
                {
                    b.Navigation("Obstacles");
                });
#pragma warning restore 612, 618
        }
    }
}
